"""empty message

Revision ID: 576a40ca4c0f
Revises: 8a7103714f98
Create Date: 2023-05-14 12:43:23.406247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576a40ca4c0f'
down_revision = '8a7103714f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dimension', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('terrain')
        batch_op.drop_column('dimension')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
