"""empty message

Revision ID: 7026626c04f8
Revises: 576a40ca4c0f
Create Date: 2023-05-14 12:44:47.129760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7026626c04f8'
down_revision = '576a40ca4c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('dimension',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('dimension',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
